// Compile src/content/*.mdx into importable Hono/JSX modules + a typed registry.
// Run by `npm run build:posts` before dev/deploy.
import { compile } from '@mdx-js/mdx'
import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const contentDir = join(root, 'src/content')
const outDir = join(root, 'src/posts/generated')

/** Parse leading `--- ... ---` YAML-ish frontmatter (flat key: value pairs). */
function parseFrontmatter(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?/)
  if (!match) return { meta: {}, body: raw }
  const meta = {}
  for (const line of match[1].split('\n')) {
    const i = line.indexOf(':')
    if (i === -1) continue
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim()
  }
  return { meta, body: raw.slice(match[0].length) }
}

await rm(outDir, { recursive: true, force: true })
await mkdir(outDir, { recursive: true })

const files = (await readdir(contentDir)).filter((f) => f.endsWith('.mdx'))
const entries = []

for (const file of files) {
  const slug = file.replace(/\.mdx$/, '')
  const raw = await readFile(join(contentDir, file), 'utf8')
  const { meta, body } = parseFrontmatter(raw)
  const compiled = String(
    await compile(body, { jsxImportSource: 'hono/jsx', outputFormat: 'program', development: false })
  )
  await writeFile(join(outDir, `${slug}.js`), compiled)
  const markdown = `# ${meta.title ?? slug}\n\n${body.trim()}\n`
  entries.push({ slug, meta, markdown })
}

// Newest first by `order` (higher = newer)
entries.sort((a, b) => Number(b.meta.order ?? 0) - Number(a.meta.order ?? 0))

const imports = entries.map((e, i) => `import Body${i} from './${e.slug}.js'`).join('\n')
const list = entries
  .map(
    (e, i) =>
      `  { slug: ${JSON.stringify(e.slug)}, title: ${JSON.stringify(e.meta.title ?? e.slug)}, date: ${JSON.stringify(
        e.meta.date ?? ''
      )}, summary: ${JSON.stringify(e.meta.summary ?? '')}, markdown: ${JSON.stringify(e.markdown)}, Body: Body${i} }`
  )
  .join(',\n')

await writeFile(
  join(outDir, 'index.js'),
  `// GENERATED by scripts/build-posts.mjs — do not edit.\n${imports}\n\nexport const posts = [\n${list}\n]\n`
)

console.log(`build-posts: compiled ${entries.length} post(s) → src/posts/generated/`)
